const CARDS = {
	Cannon: 0,
    PlusCannon: 1,
    HevyCannon: 2,
    PlasmaGun1: 3,
    PlasmaGun2: 4,
    PlasmaGun3: 5,
    Gatling1: 6,
    Gatling2: 7,
    Gatling3: 8,
    AirSpread: 9,
    RdrMissil1: 10,
    RdrMissil2: 11,
    RdrMissil3: 12,
    HeatBall1: 13,
    HeatBall2: 14,
    HeatBall3: 15,
    IceMeteor1: 16,
    IceMeteor2: 17,
    IceMeteor3: 18,
    StunNukle: 19,
    PoisNukle: 20,
    FreezNukle: 21,
    Sword: 22,
    WideSword: 23,
    LongSword: 24,
    BlazngEdge: 25,
    TidalEdge: 26,
    StrikeEdge: 27,
    ArboEdge: 28,
    BreakSabre: 29,
    GrndWave1: 30,
    GrndWave2: 31,
    GrndWave3: 32,
    JetAttack1: 33,
    JetAttack2: 34,
    JetAttack3: 35,
    PowerBomb1: 36,
    PowerBomb2: 37,
    PowerBomb3: 38,
    GhstPulse1: 39,
    GhstPulse2: 40,
    GhstPulse3: 41,
    FireRing1: 42,
    FireRing2: 43,
    FireRing3: 44,
    TimeBomb1: 45,
    TimeBomb2: 46,
    TimeBomb3: 47,
    FireBzook1: 48,
    FireBzook2: 49,
    FireBzook3: 50,
    TailBurnr1: 51,
    TailBurnr2: 52,
    TailBurnr3: 53,
    WideWave1: 54,
    WideWave2: 55,
    WideWave3: 56,
    ChainBubl1: 57,
    ChainBubl2: 58,
    ChainBubl3: 59,
    GreenInk: 60,
    BlueInk: 61,
    PurpleInk: 62,
    StikyRain1: 63,
    StikyRain2: 64,
    StikyRain3: 65,
    CloudShot1: 66,
    CloudShot2: 67,
    CloudShot3: 68,
    ThndrBall1: 69,
    ThndrBall2: 70,
    ThndrBall3: 71,
    VolticEye1: 72,
    VolticEye2: 73,
    VolticEye3: 74,
    FlickrKck1: 75,
    FlickrKck2: 76,
    FlickrKck3: 77,
    JumboHmmr1: 78,
    JumboHmmr2: 79,
    JumboHmmr3: 80,
    MopLance1: 81,
    MopLance2: 82,
    MopLance3: 83,
    'Fokx-Fu1': 84,
    'Fokx-Fu2': 85,
    'Fokx-Fu3': 86,
    VulcnSeed1: 87,
    VulcnSeed2: 88,
    VulcnSeed3: 89,
    BraveSwrd1: 90,
    BraveSwrd2: 91,
    BraveSwrd3: 92,
    JunkCube1: 93,
    JunkCube2: 94,
    JunkCube3: 95,
    SyncHook1: 96,
    SyncHook2: 97,
    SyncHook3: 98,
    PowerSong: 99,
    QuakeSong: 100,
    TripSong: 101,
    MoaiFall1: 102,
    MoaiFall2: 103,
    MoaiFall3: 104,
    BigAx1: 105,
    BigAx2: 106,
    BigAx3: 107,
    MagiCrysl1: 108,
    MagiCrysl2: 109,
    MagiCrysl3: 110,
    BlackHole1: 111,
    BlackHole2: 112,
    BlackHole3: 113,
    BrsrkSwrd1: 114,
    BrsrkSwrd2: 115,
    BrsrkSwrd3: 116,
    GreenBurst: 117,
    IceBurst: 118,
    PoisBurst: 119,
    TyphnDance: 120,
    JamminPnch: 121,
    JamMachGun: 122,
    Whistle: 123,
    Bombalizer: 124,
    AntiSword: 125,
    Recover10: 126,
    Recover30: 127,
    Recover50: 128,
    Recover80: 129,
    Recover120: 130,
    Recover150: 131,
    Recover200: 132,
    Recover300: 133,
    Barrier: 134,
    Barrier100: 135,
    Barrier200: 136,
    Aura: 137,
    Invisible: 138,
    SpiritFury: 139,
    PoisnApple: 140,
    DoublCross: 141,
    GigaMine: 142,
    GrassStage: 143,
    IceStage: 144,
    GraviStage: 145,
    GNullStage: 146,
    HolyPanel: 147,
    ParlyzPlus: 148,
    'Attack+10': 149,
    TaurusFire: 150,
    TaursFireEX: 151,
    TaursFireSP: 152,
    CygnusWing: 153,
    CygnsWingEX: 154,
    CygnsWingSP: 155,
    HarpNote: 156,
    HarpNoteEX: 157,
    HarpNoteSP: 158,
    LibraScals: 159,
    LibrScalsEX: 160,
    LibrScalsSP: 161,
    QnOphiuca: 162,
    QnOphiucaEX: 163,
    QnOphiucaSP: 164,
    GeminSpark: 165,
    GemnSpkEX: 166,
    GemnSpkSP: 167,
    CancrBuble: 168,
    CancrBublEX: 169,
    CancrBublSP: 170,
    WolfWoods: 171,
    WolfWoodsEX: 172,
    WolfWoodsSP: 173,
    CrwnThundr: 174,
    CrwnThndrEX: 175,
    CrwnThndrSP: 176,
    PegasusMgc: 177,
    PegasuMgcEX: 178,
    PegasuMgcSP: 179,
    LeoKingdom: 180,
    LeoKingdmEX: 181,
    LeoKingdmSP: 182,
    DragonSky: 183,
    DragonSkyEX: 184,
    DragonSkySP: 185
};

const STANDARD = [
	"Cannon",
    "PlusCannon",
    "HevyCannon",
    "PlasmaGun1",
    "PlasmaGun2",
    "PlasmaGun3",
    "Gatling1",
    "Gatling2",
    "Gatling3",
    "AirSpread",
    "RdrMissil1",
    "RdrMissil2",
    "RdrMissil3",
    "HeatBall1",
    "HeatBall2",
    "HeatBall3",
    "IceMeteor1",
    "IceMeteor2",
    "IceMeteor3",
    "StunNukle",
    "PoisNukle",
    "FreezNukle",
    "Sword",
    "WideSword",
    "LongSword",
    "BlazngEdge",
    "TidalEdge",
    "StrikeEdge",
    "ArboEdge",
    "BreakSabre",
    "GrndWave1",
    "GrndWave2",
    "GrndWave3",
    "JetAttack1",
    "JetAttack2",
    "JetAttack3",
    "PowerBomb1",
    "PowerBomb2",
    "PowerBomb3",
    "GhstPulse1",
    "GhstPulse2",
    "GhstPulse3",
    "FireRing1",
    "FireRing2",
    "FireRing3",
    "TimeBomb1",
    "TimeBomb2",
    "TimeBomb3",
    "FireBzook1",
    "FireBzook2",
    "FireBzook3",
    "TailBurnr1",
    "TailBurnr2",
    "TailBurnr3",
    "WideWave1",
    "WideWave2",
    "WideWave3",
    "ChainBubl1",
    "ChainBubl2",
    "ChainBubl3",
    "GreenInk",
    "BlueInk",
    "PurpleInk",
    "StikyRain1",
    "StikyRain2",
    "StikyRain3",
    "CloudShot1",
    "CloudShot2",
    "CloudShot3",
    "ThndrBall1",
    "ThndrBall2",
    "ThndrBall3",
    "VolticEye1",
    "VolticEye2",
    "VolticEye3",
    "FlickrKck1",
    "FlickrKck2",
    "FlickrKck3",
    "JumboHmmr1",
    "JumboHmmr2",
    "JumboHmmr3",
    "MopLance1",
    "MopLance2",
    "MopLance3",
    "Fokx-Fu1",
    "Fokx-Fu2",
    "Fokx-Fu3",
    "VulcnSeed1",
    "VulcnSeed2",
    "VulcnSeed3",
    "BraveSwrd1",
    "BraveSwrd2",
    "BraveSwrd3",
    "JunkCube1",
    "JunkCube2",
    "JunkCube3",
    "SyncHook1",
    "SyncHook2",
    "SyncHook3",
    "PowerSong",
    "QuakeSong",
    "TripSong",
    "MoaiFall1",
    "MoaiFall2",
    "MoaiFall3",
    "BigAx1",
    "BigAx2",
    "BigAx3",
    "MagiCrysl1",
    "MagiCrysl2",
    "MagiCrysl3",
    "BlackHole1",
    "BlackHole2",
    "BlackHole3",
    "BrsrkSwrd1",
    "BrsrkSwrd2",
    "BrsrkSwrd3",
    "GreenBurst",
    "IceBurst",
    "PoisBurst",
    "TyphnDance",
    "JamminPnch",
    "JamMachGun",
    "Whistle",
    "Bombalizer",
    "AntiSword",
    "Recover10",
    "Recover30",
    "Recover50",
    "Recover80",
    "Recover120",
    "Recover150",
    "Recover200",
    "Recover300",
    "Barrier",
    "Barrier100",
    "Barrier200",
    "Aura",
    "Invisible",
    "SpiritFury",
    "PoisnApple",
    "DoublCross",
    "GigaMine",
    "GrassStage",
    "IceStage",
    "GraviStage",
    "GNullStage",
    "HolyPanel",
    "ParlyzPlus",
    "Attack+10"
];

const MEGA = [
    "TaurusFire",
    "TaursFireEX",
    "TaursFireSP",
    "CygnusWing",
    "CygnsWingEX",
    "CygnsWingSP",
    "HarpNote",
    "HarpNoteEX",
    "HarpNoteSP",
    "LibraScals",
    "LibrScalsEX",
    "LibrScalsSP",
    "QnOphiuca",
    "QnOphiucaEX",
    "QnOphiucaSP",
    "GeminSpark",
    "GemnSpkEX",
    "GemnSpkSP",
    "CancrBuble",
    "CancrBublEX",
    "CancrBublSP",
    "WolfWoods",
    "WolfWoodsEX",
    "WolfWoodsSP",
    "CrwnThundr",
    "CrwnThndrEX",
    "CrwnThndrSP",
    "PegasusMgc",
    "PegasuMgcEX",
    "PegasuMgcSP",
    "LeoKingdom",
    "LeoKingdmEX",
    "LeoKingdmSP",
    "DragonSky",
    "DragonSkyEX",
    "DragonSkySP"
];

const CARDNAMES = STANDARD.concat(MEGA);